apiVersion: secrets-store.csi.x-k8s.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
spec:
  provider:
    azure:
      tenantId: "<your-azure-tenant-id>"
      keyVaultName: "sample-azure-kv"
      cloudName: AzurePublicCloud
      useVMManagedIdentity: true
