apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-static-pvc
  namespace: sample-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: azure-static-pv
  storageClassName: azure-managed-premium
